/*

2. Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Source and copyright at: https://projecteuler.net/problem=2

*/

public class 2_EvenFibonacciNumbers{

    public static void main(String[ ] args){
 
        int answer = 0;
        int i = 0;
        int j = 1;
        int temp;
        while (j < 4000000){ 
            temp  = j; 
            j = i + j;
            if ((j % 2) == 0 ){
                answer += j;
            }    
            i = temp;
        }
        System.out.println(answer);
    }  
} 
